COMPILER	= gcc
FLAGS		= -pedantic -std=c99 -Wall
DEBUG		= -fsanitize=address -g

OUTPUT_FILE_MON	= bikeSharingMON
OUTPUT_FILE_NYC	= bikeSharingNYC

QUERIES		= query1.csv query2.csv query3.csv

DEPENDENCIES	= stationsADT.c queries.c fileParsing.c htmlTable.c

all: MON NYC

debug: COMPILER+=$(DEBUG)
debug: all

MON: fileMON.o
	$(COMPILER) -o $(OUTPUT_FILE_MON) $(FLAGS)

NYC: fileNYC.o
	$(COMPILER) -o $(OUTPUT_FILE_NYC) $(FLAGS)

fileMON.o: bikeSharingMON.c
	$(COMPILER) -c bikeSharingMON.c $(DEPENDENCIES) $(FLAGS) 

fileNYC.o: bikeSharingNYC.c
	$(COMPILER) -c bikeSharingNYC.c $(DEPENDENCIES) $(FLAGS) 
	
clean:
	rm -rf $(OUTPUT_FILE_MON) $(OUTPUT_FILE_NYC) *.o

cleanMON:
	rm -rf $(OUTPUT_FILE_MON) *.o

cleanNYC:
	rm -rf $(OUTPUT_FILE_NYC) *.o

cleanQueries:
	rm -f $(QUERIES)

